# Generated by Django 3.2.4 on 2021-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(choices=[('Black', 'BLACK'), ('White', 'WHITE'), ('Red', 'RED'), ('Green', 'GREEN'), ('Blue', 'BLUE')], default='Black', max_length=20),
        ),
    ]
