# Generated by Django 3.2.4 on 2021-06-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='Man')),
                ('category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='MyApp2.category')),
            ],
            options={
                'verbose_name': 'Woman',
                'verbose_name_plural': 'Women',
            },
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='Man')),
                ('category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='MyApp2.category')),
            ],
            options={
                'verbose_name': 'Man',
                'verbose_name_plural': 'Men',
            },
        ),
    ]
