# Generated by Django 3.2.4 on 2021-06-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
