# Generated by Django 3.2.4 on 2021-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='photo',
            field=models.ImageField(upload_to='Woman'),
        ),
    ]
